# render.yaml — Ghost CMS on Render (Docker, Blueprint schema-compliant)

databases:
  - name: ghost-db
    plan: free
    databaseName: ghost
    user: ghost_user

services:
  - type: web
    name: ghost
    runtime: docker            # ⬅️ use 'runtime', not 'env'
    plan: starter
    region: oregon
    dockerfilePath: Dockerfile
    healthCheckPath: /
    autoDeploy: true

    envVars:
      - key: NODE_ENV
        value: production
      - key: url
        value: https://yourapp.onrender.com
      - key: server__host
        value: 0.0.0.0
      - key: server__port
        value: 10000

      # Database config (single connection string from the DB resource)
      - key: database__client
        value: pg
      - key: database__connection__connectionString
        fromDatabase:
          name: ghost-db
          property: connectionString

      # Helpful for managed Postgres SSL defaults
      - key: database__connection__ssl__rejectUnauthorized
        value: "false"

    disk:
      name: ghost-content
      mountPath: /var/lib/ghost/content
      sizeGB: 5
